server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  servlet:
    multipart:
      enabled: true
      location: D:\image
      file-size-threshold: 5MB
      max-file-size: 20MB
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/templates/
  mvc:
    static-path-pattern: /**  # 允许匹配所有静态资源路径（默认就是/**，可显式配置）

minio:
  url: http://192.168.43.20:19966  # 缩进2个空格（与accessKey对齐）
  accessKey: admin                # 同层级缩进一致
  secretKey: myj040520
  bucket-name: my-project

